/*
 * Copyright 2024, Brightspot.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gyro.google.sqladmin;

import gyro.core.resource.Diffable;
import gyro.core.validation.ValidStrings;
import gyro.google.Copyable;

public class SqlOutOfDiskReport extends Diffable
    implements Copyable<com.google.api.services.sqladmin.model.SqlOutOfDiskReport> {

    private Integer sqlMinRecommendedIncreaseSizeGb;

    private String sqlOutOfDiskState;

    /**
     * The minimum recommended increase size in GigaBytes This field is consumed by the frontend * Writers: * the proactive database wellness job for OOD. * Readers:
     */
    public Integer getSqlMinRecommendedIncreaseSizeGb() {
        return sqlMinRecommendedIncreaseSizeGb;
    }

    public void setSqlMinRecommendedIncreaseSizeGb(Integer sqlMinRecommendedIncreaseSizeGb) {
        this.sqlMinRecommendedIncreaseSizeGb = sqlMinRecommendedIncreaseSizeGb;
    }

    /**
     * This field represents the state generated by the proactive database wellness job for OutOfDisk issues. * Writers: * the proactive database wellness job for OOD. * Readers: * the proactive database wellness job
     */
    @ValidStrings({
        "SQL_OUT_OF_DISK_STATE_UNSPECIFIED",
        "NORMAL",
        "SOFT_SHUTDOWN"
    })
    public String getSqlOutOfDiskState() {
        return sqlOutOfDiskState;
    }

    public void setSqlOutOfDiskState(String sqlOutOfDiskState) {
        this.sqlOutOfDiskState = sqlOutOfDiskState;
    }

    @Override
    public String primaryKey() {
        return "";
    }

    @Override
    public void copyFrom(com.google.api.services.sqladmin.model.SqlOutOfDiskReport model) {
        setSqlMinRecommendedIncreaseSizeGb(model.getSqlMinRecommendedIncreaseSizeGb());
        setSqlOutOfDiskState(model.getSqlOutOfDiskState());
    }
}
