/*
 * Copyright 2024, Brightspot.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gyro.google.cloudsql;

import com.google.api.services.sqladmin.model.SqlOutOfDiskReport;
import gyro.core.resource.Diffable;
import gyro.core.resource.Output;
import gyro.google.Copyable;

public class DbSqlOutOfDiskReport extends Diffable implements Copyable<SqlOutOfDiskReport> {

    private Integer sqlMinRecommendedIncreaseSizeGb;
    private String sqlOutOfDiskState;

    /**
     * The minimum recommended increase size in GigaBytes.
     */
    @Output
    public Integer getSqlMinRecommendedIncreaseSizeGb() {
        return sqlMinRecommendedIncreaseSizeGb;
    }

    public void setSqlMinRecommendedIncreaseSizeGb(Integer sqlMinRecommendedIncreaseSizeGb) {
        this.sqlMinRecommendedIncreaseSizeGb = sqlMinRecommendedIncreaseSizeGb;
    }

    /**
     * The state generated by the proactive database wellness job for OutOfDisk issues.
     */
    @Output
    public String getSqlOutOfDiskState() {
        return sqlOutOfDiskState;
    }

    public void setSqlOutOfDiskState(String sqlOutOfDiskState) {
        this.sqlOutOfDiskState = sqlOutOfDiskState;
    }

    @Override
    public void copyFrom(SqlOutOfDiskReport model) throws Exception {
        setSqlMinRecommendedIncreaseSizeGb(model.getSqlMinRecommendedIncreaseSizeGb());
        setSqlOutOfDiskState(model.getSqlOutOfDiskState());
    }

    @Override
    public String primaryKey() {
        return "";
    }
}
